import { type Href, useLocalSearchParams, useRouter } from 'expo-router';
import { useEffect, useState } from 'react';
import { ActivityIndicator, Alert, Image, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { AppBackground, RequestHeader } from '../../../components/RequestFlowUI';
import { useAuth } from '../../../context/AuthContext';
import { confirmAssignedVolunteer, getRequestById } from '../../../services/requestService';
import { colors } from '../../../theme/colors';
import type { CompanionshipRequest } from '../../../types/request';

export default function VolunteerProfile() {
  const { requestId } = useLocalSearchParams<{ requestId: string }>(); const { user } = useAuth(); const router = useRouter(); const [request, setRequest] = useState<CompanionshipRequest | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState(false);
  useEffect(() => { if (user && requestId) getRequestById(requestId, user.uid).then(setRequest).catch(() => setError(true)); }, [requestId, user]);
  async function confirm() { if (!user || !requestId) return; setBusy(true); try { await confirmAssignedVolunteer(requestId, user.uid); Alert.alert('Volunteer confirmed', 'Your visit is now scheduled.', [{ text: 'View Request', onPress: () => router.replace(`/(elderly)/request-details/${requestId}` as Href) }]); } catch { Alert.alert("We couldn't confirm this volunteer", 'Please refresh the request and try again.'); } finally { setBusy(false); } }
  if (error) return <SafeAreaView style={styles.safe}><View style={styles.center}><Text style={styles.title}>Profile unavailable</Text><Text style={styles.body}>This volunteer is not assigned to your request.</Text></View></SafeAreaView>;
  if (!request) return <SafeAreaView style={styles.safe}><View style={styles.center}><ActivityIndicator size="large" color={colors.primary} /></View></SafeAreaView>;
  const name = request.volunteerName || 'SilverLink volunteer';
  return <SafeAreaView style={styles.safe} edges={['top']}><AppBackground><RequestHeader title="Volunteer Profile" onBack={() => router.back()} /><ScrollView contentContainerStyle={styles.content}>{request.volunteerPhotoUrl ? <Image source={{ uri: request.volunteerPhotoUrl }} accessibilityLabel={`${name}'s profile photo`} style={styles.photo} /> : <View style={styles.avatar}><Text style={styles.avatarText}>{name.charAt(0).toUpperCase()}</Text></View>}<Text style={styles.title}>{name}</Text>{request.volunteerVerified ? <Text style={styles.verified}>✓ Verified SilverLink volunteer</Text> : <Text style={styles.pending}>Verification not confirmed</Text>}<View style={styles.card}><Info label="About" value={request.volunteerBio} fallback="This volunteer has not added an introduction yet." /><Info label="Experience" value={request.volunteerExperience} fallback="Experience information has not been added." />{request.volunteerRating !== undefined ? <Info label="Rating" value={`${request.volunteerRating.toFixed(1)} out of 5`} /> : null}</View><View style={styles.trust}><Text style={styles.trustTitle}>Before you confirm</Text><Text style={styles.body}>Review the volunteer details above. SilverLink only displays information the volunteer has made available for companionship requests.</Text></View>{request.status === 'accepted' ? <Pressable accessibilityRole="button" accessibilityState={{ busy }} disabled={busy} style={styles.confirm} onPress={() => void confirm()}>{busy ? <ActivityIndicator color={colors.textOnPrimary} /> : <Text style={styles.confirmText}>Accept This Volunteer</Text>}</Pressable> : <View style={styles.scheduled}><Text style={styles.scheduledText}>✓ You have confirmed this volunteer</Text></View>}</ScrollView></AppBackground></SafeAreaView>;
}
function Info({ label, value, fallback }: { label: string; value?: string; fallback?: string }) { return <View style={styles.info}><Text style={styles.label}>{label.toUpperCase()}</Text><Text style={styles.value}>{value || fallback}</Text></View>; }
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.background }, center: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 25 }, content: { padding: 22, paddingBottom: 42, alignItems: 'center' }, photo: { width: 116, height: 116, borderRadius: 58, backgroundColor: colors.surfaceSoft }, avatar: { width: 116, height: 116, borderRadius: 58, backgroundColor: colors.primaryLight, alignItems: 'center', justifyContent: 'center' }, avatarText: { color: colors.primary, fontSize: 46, fontWeight: '900' }, title: { color: colors.textPrimary, fontSize: 27, fontWeight: '900', textAlign: 'center', marginTop: 17 }, body: { color: colors.textSecondary, fontSize: 16, lineHeight: 24, textAlign: 'center', marginTop: 7 }, verified: { color: colors.success, fontSize: 16, fontWeight: '800', marginTop: 8 }, pending: { color: colors.warning, fontSize: 16, fontWeight: '800', marginTop: 8 }, card: { width: '100%', backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: 19, padding: 18, marginTop: 24 }, info: { paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: colors.border }, label: { color: colors.textSecondary, fontSize: 13, fontWeight: '900', letterSpacing: 0.6 }, value: { color: colors.textPrimary, fontSize: 17, lineHeight: 24, fontWeight: '700', marginTop: 6 }, trust: { width: '100%', borderRadius: 17, backgroundColor: colors.primaryLight, borderWidth: 1, borderColor: '#C7D2FE', padding: 17, marginTop: 14 }, trustTitle: { color: colors.primaryDark, fontSize: 18, fontWeight: '900', textAlign: 'center' }, confirm: { width: '100%', minHeight: 58, borderRadius: 15, backgroundColor: colors.primary, alignItems: 'center', justifyContent: 'center', marginTop: 20 }, confirmText: { color: colors.textOnPrimary, fontSize: 18, fontWeight: '900' }, scheduled: { width: '100%', minHeight: 58, borderRadius: 15, backgroundColor: colors.successLight, alignItems: 'center', justifyContent: 'center', marginTop: 20 }, scheduledText: { color: colors.success, fontSize: 17, fontWeight: '900' } });
