// SilverLink sage palette. Text/background pairs meet WCAG AA (4.5:1) for body text.
export const colors = {
  primary: '#3E6A52',
  primaryDark: '#2C4F3C',
  primaryLight: '#DDEAE1',
  primaryBorder: '#B9D0C0',
  secondary: '#6F8F7B',
  secondaryLight: '#E8F0EA',
  secondaryBorder: '#C9D9CD',
  accent: '#C9D9CD',
  background: '#EEF4EF',
  surface: '#FFFFFF',
  surfaceSoft: '#F4F8F5',
  textPrimary: '#1D2B23',
  textSecondary: '#4E6157',
  textMuted: '#6B7D72',
  textOnPrimary: '#FFFFFF',
  textOnPrimaryMuted: 'rgba(255,255,255,0.85)',
  border: '#D6E2D9',
  borderDark: '#B9CABE',
  success: '#2F7A4B',
  successLight: '#DCEFE2',
  successText: '#1F5A35',
  warning: '#B7791F',
  warningLight: '#FBF0DA',
  warningText: '#7A4E0E',
  error: '#B3261E',
  errorLight: '#FBE3E1',
  errorBorder: '#F0B4AE',
  errorText: '#8C1D17',
  info: '#2F6F8F',
  infoLight: '#DDEDF4',
  infoBorder: '#B3D3E2',
  infoText: '#1D4E66',
  star: '#C98A12',
  inputBackground: '#FFFFFF',
  inputBorder: '#B9CABE',
  inputPlaceholder: '#7A8B80',
  disabled: '#C9D5CC',
  disabledText: '#5E6F64',
  overlay: 'rgba(29, 43, 35, 0.32)',
  shadow: '#1D2B23',
  elderly: '#3E6A52',
  caregiver: '#5B7F6A',
  volunteer: '#2F6F8F',
  admin: '#4E6157',
} as const;

// Shared status badge colours so every role sees the same meaning for a status.
export const statusColors: Record<string, { bg: string; text: string }> = {
  pending: { bg: colors.warningLight, text: colors.warningText },
  accepted: { bg: colors.infoLight, text: colors.infoText },
  scheduled: { bg: colors.primaryLight, text: colors.primaryDark },
  in_progress: { bg: colors.successLight, text: colors.successText },
  completed: { bg: colors.successLight, text: colors.successText },
  cancelled: { bg: colors.errorLight, text: colors.errorText },
};
