import { useState } from 'react';
import { ActivityIndicator, Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useAuth } from '../../context/AuthContext';
import { logoutUser } from '../../services/authService';
import { updateUserProfile } from '../../services/userService';
import { colors } from '../../theme/colors';

export default function Profile() {
  const { profile, user, retryProfile } = useAuth(); const [editing, setEditing] = useState(false); const [saving, setSaving] = useState(false); const [fullName, setFullName] = useState(profile?.fullName ?? ''); const [phone, setPhone] = useState(profile?.phone ?? ''); const [locality, setLocality] = useState(profile?.locality ?? ''); const [language, setLanguage] = useState(profile?.preferredLanguage ?? '');
  async function save() { if (!user || fullName.trim().length < 2) return Alert.alert('Check your name', 'Please enter your full name.'); setSaving(true); try { await updateUserProfile(user.uid, { fullName, phone, locality, preferredLanguage: language }); await retryProfile(); setEditing(false); Alert.alert('Profile updated', 'Your information has been saved.'); } catch { Alert.alert("We couldn't update your profile", 'Please try again.'); } finally { setSaving(false); } }
  const name = profile?.fullName || user?.displayName || 'SilverLink member';
  return <SafeAreaView style={styles.safe}><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={styles.content}><View style={styles.avatar}><Text style={styles.avatarText}>{name.charAt(0).toUpperCase()}</Text></View>{editing ? <View style={styles.form}><Field label="Full name" value={fullName} onChangeText={setFullName} /><Field label="Phone number" value={phone} onChangeText={setPhone} /><Field label="Locality" value={locality} onChangeText={setLocality} /><Field label="Preferred language" value={language} onChangeText={setLanguage} /><Pressable accessibilityRole="button" disabled={saving} style={styles.primary} onPress={() => void save()}>{saving ? <ActivityIndicator color={colors.textOnPrimary} /> : <Text style={styles.primaryText}>Save Profile</Text>}</Pressable><Pressable accessibilityRole="button" style={styles.cancel} onPress={() => setEditing(false)}><Text style={styles.cancelText}>Cancel</Text></Pressable></View> : <><Text style={styles.name}>{name}</Text><Text style={styles.email}>{profile?.email || user?.email}</Text><Info label="Phone" value={profile?.phone} /><Info label="Locality" value={profile?.locality} /><Info label="Preferred language" value={profile?.preferredLanguage} /><Pressable accessibilityRole="button" style={styles.primary} onPress={() => setEditing(true)}><Text style={styles.primaryText}>Edit Profile</Text></Pressable><Pressable accessibilityRole="button" style={styles.button} onPress={logoutUser}><Text style={styles.buttonText}>Log Out</Text></Pressable></>}</ScrollView></SafeAreaView>;
}
function Info({ label, value }: { label: string; value?: string }) { return <View style={styles.info}><Text style={styles.infoLabel}>{label}</Text><Text style={styles.infoValue}>{value || 'Not added'}</Text></View>; } function Field({ label, value, onChangeText }: { label: string; value: string; onChangeText: (value: string) => void }) { return <View><Text style={styles.infoLabel}>{label}</Text><TextInput accessibilityLabel={label} value={value} onChangeText={onChangeText} style={styles.input} placeholderTextColor={colors.inputPlaceholder} /></View>; }

const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.background }, content: { flexGrow: 1, alignItems: 'center', justifyContent: 'center', padding: 24, paddingBottom: 40 }, avatar: { width: 82, height: 82, borderRadius: 41, backgroundColor: colors.primaryLight, alignItems: 'center', justifyContent: 'center' }, avatarText: { color: colors.primary, fontSize: 34, fontWeight: '800' }, name: { color: colors.textPrimary, fontSize: 25, fontWeight: '800', marginTop: 16, textAlign: 'center' }, email: { color: colors.textSecondary, fontSize: 16, marginTop: 6, marginBottom: 20 }, info: { width: '100%', backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: 14, padding: 14, marginTop: 9 }, infoLabel: { color: colors.textSecondary, fontSize: 14, fontWeight: '800', marginBottom: 6 }, infoValue: { color: colors.textPrimary, fontSize: 17, fontWeight: '700' }, form: { width: '100%', gap: 14, marginTop: 22 }, input: { minHeight: 54, borderWidth: 1, borderColor: colors.inputBorder, borderRadius: 13, backgroundColor: colors.surface, paddingHorizontal: 14, color: colors.textPrimary, fontSize: 17 }, primary: { width: '100%', minHeight: 54, marginTop: 20, borderRadius: 14, backgroundColor: colors.primary, alignItems: 'center', justifyContent: 'center' }, primaryText: { color: colors.textOnPrimary, fontSize: 17, fontWeight: '800' }, cancel: { minHeight: 52, alignItems: 'center', justifyContent: 'center' }, cancelText: { color: colors.textSecondary, fontSize: 16, fontWeight: '800' }, button: { minWidth: 170, minHeight: 54, marginTop: 14, borderRadius: 14, borderWidth: 2, borderColor: colors.primary, alignItems: 'center', justifyContent: 'center' }, buttonText: { color: colors.primary, fontSize: 17, fontWeight: '800' } });
